[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "goldenfish-api"